### ISSUE TITLE
Fix issues with the way this repo was created.

### ISSUE THREAD

**Issue by mariospr** [vrutkovs/flatpak-thunderbird#3]
I have a small comment about this particular fork of my repo: 

While I'm more than happy for you (or anyone) to fork this experiment of mine (otherwise I wouldn't have licensed it as "CC0 1.0 Universal license"), I would have appreciated if you would have done 2 things:

  1. Instead of simply committing the files of my repo as a new repo and create a [single commit with them as if they were created by you](https://github.com/vrutkovs/flatpak-thunderbird/commit/969cdc3a1e950240a2549393b020ccca2a53cd2b), I think it would have been better if you cloned/forked the original repo instead, and put your modifications on top. That way history would be preserved and someone (including you) running `git blame` would have got a meaningful output.

  2. There are links to my personal github repo in the [`Prebuilt flatpaks` section of the README file](https://github.com/vrutkovs/flatpak-thunderbird/commit/969cdc3a1e950240a2549393b020ccca2a53cd2b#diff-04c6e90faac2675aa89e2176d2eec7d8R53), so I think you should either remove that section entirerly from that file in your repo or provide those binaries yourself through your means.

Since you have this repo created already, and specially after seeing that this is already being handled in flatpak in https://github.com/flathub/flathub/pull/161, I'm not particularly concerned about (1), since that would require to change the history of your already existing repo and force-push, so I don't think it's necessary. Just mentioning it because that's how I would do it if I was the one forking the repo.

About (2), however, I would like to have that **fixed** since I don't like being linked to binaries I uploaded to my personal repo, as I think that's not right. Actually, I'm thinking I'll probably remove those binaries anyway to avoid confusion with flathub and to prevent people from installing outdated versions, so your links will be dead anyway.

**Comment by mariospr** [comment]
Here you have a PR: https://github.com/vrutkovs/flatpak-thunderbird/pull/4

Fun fact: related to my point (1) above, note that I needed to [fork your "fork"](https://github.com/mariospr/vrutkovs-thunderbird) of my [own original repo](https://github.com/mariospr/thunderbird-flatpak) just to make this PR, which wouldn't have been the case if you just forked it in the first place, since github would allow me to do the PR easily otherwise...

**Comment by vrutkovs** [comment]
Oh, good catch, not sure why this repo wasn't a correct fork. Probably due to the binaries being in the repo I didn't click 'Fork' button but created a repo from scratch - it was a mistake :(

Fixed (1) by rebasing the repo and fixed (2) by cherry-picking that commit (thanks!).

**Comment by mariospr** [comment]
Ah! That thing about the binaries is actually a very good point. It would have made your repo unnecessarily big for no good reason. So, while it seems like you could have worked around that with some git "surgery", it's true I didn't make it easy by uploading those massive files there. Point taken :)

**Comment by mariospr** [comment]
Looks like this can be closed now. Thanks!
